# CONVOLUTIONAL NEURAL NETWORK

Importing the Libraries

In [1]:
import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator

## Part 1: Preprocessing the Dataset

Preprocessing the Training Set

In [2]:
class_labels = ['Apple Braeburn', 'Apple Crimson Snow', 'Apple Golden 1', 'Apple Golden 2', 'Apple Golden 3',
                'Apple Granny Smith', 'Apple Pink Lady', 'Apple Red 1', 'Apple Red 2', 'Apple Red 3', 'Apple Red Delicious',
                'Apple Red Yellow 1', 'Apple Red Yellow 2', 'Apricot', 'Avocado', 'Avocado ripe', 'Banana', 'Banana Lady Finger',
                'Banana Red', 'Beetroot', 'Blueberry', 'Cactus fruit', 'Cantaloupe 1', 'Cantaloupe 2', 'Carambula', 
                'Cauliflower', 'Cherry 1', 'Cherry 2', 'Cherry Rainier', 'Cherry Wax Black', 'Cherry Wax Red', 
                'Cherry Wax Yellow', 'Chestnut', 'Clementine', 'Cocos', 'Corn', 'Corn Husk', 'Cucumber Ripe', 'Cucumber Ripe 2',
                'Dates', 'Eggplant', 'Fig', 'Ginger Root', 'Granadilla', 'Grape Blue', 'Grape Pink', 'Grape White', 
                'Grape White 2', 'Grape White 3', 'Grape White 4', 'Grapefruit Pink', 'Grapefruit White', 'Guava', 'Hazelnut', 
                'Huckleberry', 'Kaki', 'Kiwi', 'Kohlrabi', 'Kumquats', 'Lemon', 'Lemon Meyer', 'Limes', 'Lychee', 'Mandarine', 
                'Mango', 'Mango Red', 'Mangostan', 'Maracuja', 'Melon Piel de Sapo', 'Mulberry', 'Nectarine', 'Nectarine Flat', 
                'Nut Forest', 'Nut Pecan', 'Onion Red', 'Onion Red Peeled', 'Onion White', 'Orange', 'Papaya', 'Passion Fruit', 
                'Peach', 'Peach 2', 'Peach Flat', 'Pear', 'Pear 2', 'Pear Abate', 'Pear Forelle', 'Pear Kaiser', 'Pear Monster',
                'Pear Red', 'Pear Stone', 'Pear Williams', 'Pepino', 'Pepper Green', 'Pepper Orange', 'Pepper Red', 
                'Pepper Yellow', 'Physalis', 'Physalis with Husk', 'Pineapple', 'Pineapple Mini', 'Pitahaya Red', 'Plum', 
                'Plum 2', 'Plum 3', 'Pomegranate', 'Pomelo Sweetie', 'Potato Red', 'Potato Red Washed', 'Potato Sweet', 
                'Potato White', 'Quince', 'Rambutan', 'Raspberry', 'Redcurrant', 'Salak', 'Strawberry', 'Strawberry Wedge', 
                'Tamarillo', 'Tangelo', 'Tomato 1', 'Tomato 2', 'Tomato 3', 'Tomato 4', 'Tomato Cherry Red', 'Tomato Heart', 
                'Tomato Maroon', 'Tomato Yellow', 'Tomato not Ripened', 'Walnut', 'Watermelon']

In [3]:
training_data = tf.keras.preprocessing.image_dataset_from_directory(
    'fruits_360_dataset/fruits_360/Training',
    labels="inferred",
    label_mode='categorical',
    class_names=class_labels,
    color_mode="rgb",
    batch_size=32,
    image_size=(256, 256),
    shuffle=True
)

Found 67692 files belonging to 131 classes.


Preprocessing the Testing Set

In [4]:
testing_data = tf.keras.preprocessing.image_dataset_from_directory(
    'fruits_360_dataset/fruits_360/Test',
    labels="inferred",
    label_mode='categorical',
    class_names=class_labels,
    color_mode="rgb",
    batch_size=32,
    image_size=(256, 256),
    shuffle=True
)

Found 22688 files belonging to 131 classes.


## Part 2: Building the CNN

Initialising the CNN

In [5]:
cnn = tf.keras.models.Sequential()

In [6]:
# Step 1 - Convolution
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu', input_shape=[256,256,3]))

In [7]:
# Step 2 - Pooling
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

In [8]:
# Adding a Second Convolutional Layer
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

In [9]:
# Step 3 - Flattening
cnn.add(tf.keras.layers.Flatten())

In [10]:
# Step 4 - Full Connection
cnn.add(tf.keras.layers.Dense(units=128, activation='relu'))

In [11]:
# Step 5 - Output Layer
cnn.add(tf.keras.layers.Dense(units=131, activation='softmax'))

## Part 3: Training the CNN

In [13]:
# Compiling the CNN
cnn.compile(optimizer= 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

Training the CNN on the Training Set and Evaluating it on the Test Set

In [14]:
cnn.fit( x= training_data, validation_data= testing_data, epochs= 4)

Epoch 1/4
2116/2116 [==============================] - 8482s 4s/step - loss: 4.1480 - accuracy: 0.8256 - val_loss: 1.4861 - val_accuracy: 0.7838
Epoch 2/4
2116/2116 [==============================] - 6176s 3s/step - loss: 0.6750 - accuracy: 0.8593 - val_loss: 3.1759 - val_accuracy: 0.7038
Epoch 3/4
2116/2116 [==============================] - 5166s 2s/step - loss: 0.3625 - accuracy: 0.9149 - val_loss: 5.1771 - val_accuracy: 0.6088
Epoch 4/4
2116/2116 [==============================] - 5737s 3s/step - loss: 0.2919 - accuracy: 0.9459 - val_loss: 4.6571 - val_accuracy: 0.6634


In [37]:
model_json = cnn.to_json()
with open("model_arch.json", "w") as json_file:
    json_file.write(model_json)
cnn.save_weights("model_weights.h5")

## Part 3: Making a Single Prediction

In [35]:
import numpy as np
from keras.preprocessing import image
test_image = image.load_img('fruits_360_dataset/fruits_360/realtime_images/image1.jpeg', target_size = (256,256))

test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)

print(test_image)
print(result)
print(training_data.class_names)

for i in class_labels:
    if (result[0][0] == i):
        prediction = class_labels[i]        


print(prediction)

[[[[198. 185. 177.]
   [198. 185. 177.]
   [198. 185. 177.]
   ...
   [181. 191. 138.]
   [181. 191. 138.]
   [182. 192. 139.]]

  [[198. 185. 177.]
   [198. 185. 177.]
   [198. 185. 177.]
   ...
   [181. 191. 138.]
   [182. 192. 139.]
   [180. 190. 137.]]

  [[196. 183. 175.]
   [199. 186. 178.]
   [199. 186. 178.]
   ...
   [178. 188. 135.]
   [181. 191. 138.]
   [181. 191. 138.]]

  ...

  [[187. 179. 168.]
   [187. 179. 168.]
   [189. 181. 170.]
   ...
   [212. 203. 194.]
   [212. 203. 194.]
   [211. 202. 193.]]

  [[187. 179. 168.]
   [187. 179. 168.]
   [189. 181. 170.]
   ...
   [212. 203. 194.]
   [211. 202. 193.]
   [211. 202. 193.]]

  [[186. 178. 167.]
   [189. 181. 170.]
   [187. 179. 168.]
   ...
   [212. 203. 194.]
   [210. 201. 192.]
   [209. 200. 191.]]]]
[[5.9374759e-20 1.8184173e-17 2.4654484e-13 3.8631755e-13 9.1949708e-38
  1.6023608e-26 2.7024120e-19 2.8677626e-11 1.8485781e-22 2.0215850e-24
  5.4982570e-09 1.5227942e-13 9.5061158e-17 1.0532342e-25 7.1986810e-16
  